apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-run-service
spec:
  template:
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/ml-cloud-run-428007/ml-run-mnist/ml-run-mnist:latest
          env:
            - name: SERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          args: ["python", "main.py"]