project_id  = "ml-cloud-run-428007"
region      = "asia-southeast1"
service_name = "ml-run-service"
image_url   = "asia-southeast1-docker.pkg.dev/ml-cloud-run-428007/ml-run/ml-run:latest"
cpu         = "2"
memory      = "2Gi"
